---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hello

resources:
  - manifests/hello-ns.yaml
  - manifests/hello-app.yaml
  - manifests/hello-svc.yaml
  - manifests/hello-ingress.yaml
