apiVersion: v1
kind: Secret
metadata:
    name: hello-secret
    namespace: hello
type: Opaque
data:
    #ENC[AES256_GCM,data:FUn5PPk=,iv:3jI6fhyh6uyIEgmGPqK54sV/SlfTwKxF0gqpWw86I1g=,tag:hDD5G6n7bCOVNeYCZ13eow==,type:comment]
    secret: ENC[AES256_GCM,data:xfIoG4pKPGU=,iv:sUm0XVOn2BiCYDdd0a9a/kfqrjluHBoieARw8lyxyTs=,tag:5heln+XO/tNLvbzTMiCPYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-04T15:35:28Z"
    mac: ENC[AES256_GCM,data:qWbNS6bmnDfsUjBhGvix5t+3wpMKvX1ghYLuIN7xnY7QLBgoEuJ/Y2mU6lb7goTIXdYfjGzybRTdUsOa7rwPYaFeNG8Zy6f6xf9k9AzJRnWSVituzL7OP95kGc8d/aVBqQWaNr+AROv1iHPK5dO64ETX+iMy5JoJ5p5hW93rbc0=,iv://1wQB0jgaEWNXtEQUjpzcqIlwlviuc/ErGga2habGY=,tag:G9V/QJs2jantO8pMU9jq7Q==,type:str]
    pgp:
        - created_at: "2021-06-04T15:35:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1n99Uit5Lq+AQ//WJ9iVasaiK1BBYovATtPhKzAQ80nhgl86iY8v2ksoAc6
            7NclY79sNf5h2Kj8ZOaulT7EGl8PUKTNMS/0FJJsNSY3syvvd10AJBtQIiNkE6eF
            1NYm6ZL/GVTUrgD8esTvm+s3j03084CgQ5PsbLp8dYiLp4RCCJv+oNMlrXFIh4JW
            pRDL6aNhWJE+9VyXIP3iLDF+BJcqxSVJRfS6RSaSSMizgPHc0IJBWo7YSMX6KA56
            xD6pipnjxym3hiG531xRoLTIniGGiCQvR9AvwMnWqwAO+rxAGTLvhD8esNI0aId1
            g+aaMmAjzfQErLYRlFAbRoLI8gzWQD427D5B2dYlPrLh2e/j72SvPY84AoMMUbRN
            K+4gCk/fLfj7TswJzZEIwtTjsLdLV0wVXJyz8Vz9wzzhsNW+FdrrgaYZFmCRjfEh
            4IwULikigaZciwudCobNtIn36/ZphiMaRdc8LIEKCNjWO/w4DcplOjqPmT4siAd9
            wIEFQK1Km5BKDkLu33EaohMQo2wP+zIk+Z7ipSvfu7hOEcN5zoe6ICDUdodU9r4O
            xDeN452vDdr8Vj7nOtssUxM4Ac1TTJ1w1bAihDHFTqZaIYU+meywG3BPh77oyL5Q
            HbWdGABNJUCChOY/ah5ghFtH+0BDDa8KUk1jIpOFfEYaFaQb5Aa25o+ResPOC7jS
            XgHsqYkSbrTc3b6Q1ko68Pd5mepLJptnjMNRfOMMV335MCS/ctO8xChOiEXA/Cet
            HpQZp3g5lz0vy6MFOxFiwtXFgHLpC9zPR7QIjCIRsKJPlvFuP6ymkG/vmXbszP8=
            =A0NB
            -----END PGP MESSAGE-----
          fp: DE0702391D8D5255A3380CE992B13BA6C8F25EC4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
