name: "Release"

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: Login to GitHub Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        no-cache: true
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
          ghcr.io/${{ github.repository }}:latest
        build-args: |
          RELEASE_DATE=${{ env.RELEASE_DATE }}
          VERSION=${{ env.RELEASE_VERSION }}
          COMMIT=${{ github.sha }}
