name: "Release"

on:
  push:
    tags:
      - v*

permissions: 
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        export VERSION=$(echo ${GITHUB_REF##*/} | sed -e 's/^v//')
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
        export CURRENT_DATE=$(date --iso-8601=seconds)
        echo "RELEASE_DATE=$CURRENT_DATE" >> $GITHUB_ENV
    - name: "Login to GitHub Container Registry"
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        no-cache: true
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
          ghcr.io/${{ github.repository }}:latest
        build-args: |
          RELEASE_DATE=${{ env.RELEASE_DATE }}
          VERSION=${{ env.RELEASE_VERSION }}
          COMMIT=${{ github.sha }}
